build:
  environment:
    ruby: '2.2.0'

  dependencies:
    before:
      - gem update
      - sudo apt-get update
      - sudo apt-get install libav-tools -y

checks:
    ruby:
        code_rating: true
        duplicate_code: true
        style_signal_exception:
            enforced_style: semantic
        style_redundant_exception: true
        style_raise_args:
            enforced_style: exploded
        style_predicate_name: true
        style_comment_annotation: true
        rails_output: false

filter:
    excluded_paths:
        - 'test/*'