language: ruby
rvm:
- 2.0.0
- 1.9.3

env:
  - RGV=master
  - RGV=v2.0.2

  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
    - "CI=true"
    - "TRAVIS=true"
    - "HAS_JOSH_K_SEAL_OF_APPROVAL=true"
    - "LANG=en_US.UTF-8"
    - "LC_ALL=en_US.UTF-8"

after_success:
    - coveralls --verbose

notifications:
  email:
    - Sascha.Manns@directbox.com