os:
  -linux

dist: trusty

language: ruby

rvm:
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3

env:
  global:
    - JRUBY_OPTS=-Xcext.enabled=true
    - CI=true
    - TRAVIS=true
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

before_install:
  - sudo apt-get update
  - sudo apt-get install libav-tools libavcodec-extra-54

before_script:
  - rake setup

after_success:
  - CI=true TRAVIS=true coveralls --verbose

notifications:
  email:
    - samannsml@directbox.com
