language: ruby
rvm:
  - 2.0.0

env:
  global:
    - JRUBY_OPTS=-Xcext.enabled=true
    - CI=true
    - TRAVIS=true
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - RGV=master
    - RGV=v2.0.2

install:
  - sudo apt-get install ubuntu-restricted-extras ffmpeg

after_success:
    - CI=true TRAVIS=true coveralls --verbose

notifications:
  email:
    - Sascha.Manns@directbox.com

  notifications:
     irc:
       channels:
         - "chat.freenode.net#open-slx"
       on_success: [never] # default: always
       on_failure: [always] # default: always
