language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-20mode
- rbx-2

env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
    - "CI=true"
    - "TRAVIS=true"
    - "HAS_JOSH_K_SEAL_OF_APPROVAL=true"
    - "LANG=en_US.UTF-8"
    - "LC_ALL=en_US.UTF-8"