# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "bundler", "~>1.11"
gem "setup", "~>5.2"
gem "parseconfig", "~>1.0"
gem "streamio-ffmpeg", "~>2.0"
gem "rainbow", "~>2.1"
gem "addressable", "~>2.4.0"
gem "notifier", "~>0.5"
gem "youtube-dl.rb", "~>0.2.5.2015"

gem "rdoc", "~>4.0", :group => [:development, :test]
gem "coveralls", "~>0.8", :group => [:development, :test]
gem "gem-release", "~>0.7", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "hoe-git", "~>1.6", :group => [:development, :test]
gem "hoe-manns", "~>1.4", :group => [:development, :test]
gem "hoe-packaging", "~>1.1", :group => [:development, :test]
gem "hoe-rubocop", "~>1.0", :group => [:development, :test]
gem "hoe-rubygems", "~>1.0", :group => [:development, :test]
gem "hoe-seattlerb", "~>1.3", :group => [:development, :test]
gem "hoe-version", "~>1.2", :group => [:development, :test]
gem "indexer", "~>0.3", :group => [:development, :test]
gem "rake", "~>10.4", :group => [:development, :test]
gem "rspec", "~>3.4", :group => [:development, :test]
gem "rubocop", "~>0.35", :group => [:development, :test]
gem "simplecov", "~>0.11", :group => [:development, :test]
gem "bundler-audit", "~>0.4", :group => [:development, :test]
gem "manns_shared", "~>1.0", :group => [:development, :test]
gem "hoe", "~>3.14", :group => [:development, :test]

# vim: syntax=ruby
